#!/bin/bash
# /usr/bin/blurlock
source ~/.profile

# take screenshot
import -window root /tmp/screenshot.png

case $BLURLOCK in
	small)
		convert /tmp/screenshot.png -blur 0x8 /tmp/screenshotblur.png
		;;
	medium)
		convert /tmp/screenshot.png -blur 30x15 /tmp/screenshotblur.png
		;;
	big|*)
		convert /tmp/screenshot.png -blur 200x100 /tmp/screenshotblur.png
		;;
esac
# blur it small
# convert /tmp/screenshot.png -blur 0x8 /tmp/screenshotblur.png

# blur it medium
# convert /tmp/screenshot.png -blur 30x15 /tmp/screenshotblur.png

# blur it big
# convert /tmp/screenshot.png -blur 200x100 /tmp/screenshotblur.png


rm /tmp/screenshot.png

# lock the screen
i3lock -i /tmp/screenshotblur.png

# sleep 1 adds a small delay to prevent possible race conditions with suspend
sleep 1

exit 0
